apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
metadata:
  name: openshift-kernel-devel
  labels:
    machineconfiguration.openshift.io/role: worker
spec:
  config:
    ignition:
      version: 3.2.0
  extensions:
  - kernel-devel
