name: gofmt

on:
  pull_request:

jobs:
  gofmt_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - uses: actions/setup-go@main
        with:
          go-version: 1.18
      - name: run gofmt test
        run: ./automation/presubmit-tests/gofmt.sh