name: go vulnerability detect

on:
  pull_request:

jobs:
  vulnerability_detect:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - uses: actions/setup-go@main
        with:
          go-version: 1.18
      - name: run vulnerability detect
        run: make govulncheck