name: image

on:
  push:
    branches: [ main ]

jobs:
  image_build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - uses: actions/setup-go@main
      with:
          go-version: 1.18
    - name: Login to Quay
      uses: docker/login-action@v1
      with:
        registry: quay.io/sustainable_computing_io
        username: ${{ secrets.BOT_NAME }}
        password: ${{ secrets.BOT_TOKEN }}
    - name: make container
      run: make
    - name: push to quay
      run: podman push quay.io/sustainable_computing_io/kepler:latest