name: Integration test

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  integration_test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        kube_provider: [kind]
    steps:
      - uses: actions/checkout@main
      - uses: actions/setup-go@main
        with:
          go-version: 1.18
          
      - name: install kubectl
        run: curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"

      - name: start local k8s cluster
        run: make cluster-up
        env:
            CLUSTER_PROVIDER: ${{matrix.kube_provider}}
            PROMETHEUS_ENABLE: "true"
            GRAFANA_ENABLE: "false"

      - name: simple test - deploy kepler
        run: make cluster-sync
        env:
            CLUSTER_PROVIDER: ${{matrix.kube_provider}}
            CTR_CMD: docker

      - name: Login to Quay
        if: github.event_name == 'push'
        uses: docker/login-action@v1
        with:
            registry: quay.io/sustainable_computing_io
            username: ${{ secrets.BOT_NAME }}
            password: ${{ secrets.BOT_TOKEN }}

      - name: make container
        if: github.event_name == 'push'
        run: make

      - name: push to quay
        if: github.event_name == 'push'
        run: podman push quay.io/sustainable_computing_io/kepler:latest